# Generated by Django 4.1 on 2022-08-14 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_article_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
