# Generated by Django 4.1 on 2022-08-14 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_articlemetadata_article_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='metadata',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.articlemetadata'),
        ),
    ]
