# Generated by Django 4.1 on 2022-08-14 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_alter_article_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemetadata',
            name='short_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
