# Generated by Django 4.1 on 2022-08-14 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_articlemetadata_short_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='published',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_image',
            field=models.CharField(blank=True, default=True, max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
