# Generated by Django 4.1 on 2022-08-14 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_remove_article_metadata_articlemetadata_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_image',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
